name: qoi_web
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_svg: ^2.0.7
  dio: ^5.4.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  file_picker: ^6.1.1
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.0
  qr_flutter: ^4.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/forlogin.png
    - assets/adminloginlogo.png
    - assets/profloginlogo.png
    - assets/hugiologo.png
    - assets/landingdrop.png
    - assets/secdrop.png
    - assets/getstarteddrop.png
    - assets/profbanlogo.png
    - assets/adminnavban.png
    - assets/card.png
  uses-material-design: true
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk.ttf
    - family: Hugio
      fonts:
        - asset: fonts/Hugio.otf
    - family: Ds-Digital
      fonts:
        - asset: fonts/DS-DIGI.ttf
